spring:
  application:
    name : app

  data:
    redis:
      host: i13e202.p.ssafy.io
      port: 6379
      password:
      timeout: 6000

  datasource:
    url: jdbc:mysql://i13e202.p.ssafy.io/bwabwayo_db
    username: root
    password: whddnjsWkd123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: "e0925046e873c5680b35eca4994b854d"
            redirect-uri: "http://i13e202.p.ssafy.io:8081/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_image, account_email
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

jwt:
  secret: "vmfhaltmskdlstkfkdgodyroqkfwkasdadowdqfgrgsgsrgsgrgsrgsrgsefjhgku="
  access-exp-minutes: 30
  refresh-exp-minutes: 10080 #60*24*7
  header: Authorization
  type: Bearer

server:
  port: 8081

openai:
  secret-key: S13P11E202-b866ef0e-647a-4e68-aabe-9953140f6092
  chat-url: https://gms.ssafy.io/gmsapi/api.openai.com/v1/chat/completions
  chat-model: gpt-4.1-nano

  embedding-url: https://gms.ssafy.io/gmsapi/api.openai.com/v1/embeddings
  embedding-model: text-embedding-3-large

cloud:
  aws:
    credentials:
      accessKey: AKIAT6OL2UNWJPX53KGW
      secretKey: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: bwabwayo-general-bucket
    stack:
      auto: false


logging:
  level:
    com.bwabwayo.app: DEBUG
